name: bloc_architecture_app
description: A Flutetr Bloc Architecture project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.0.0
  cupertino_icons: ^1.0.0
  flutter_bloc: ^7.0.0
  hydrated_bloc: ^7.0.0
  device_preview: ^1.1.0
  flare_flutter: ^3.0.2
  sizer: ^2.0.15
  path_provider: ^2.0.11
  simple_animations: ^3.1.1
  animate_do: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
